export const USER = "USER_FETCH_DATA_SUCCESS";
export const TODOLIST = "TODOLIST_FETCH_DATA_SUCCESS";
export const POSTSLIST = "POSTSLIST_FETCH_DATA_SUCCESS";
export const ADDPOST = "ADDPOST_SEND_DATA_SUCCESS";
export const ERROR = "ERROR";